import { type ClientSchema, a, defineData } from "@aws-amplify/backend";

const schema = a.schema({
  User: a.model({
      id: a.id().required(), 
      
      firstName: a.string(),
      lastName: a.string(),
      birthday: a.date(),
      gender: a.enum(['MAN', 'WOMAN', 'NON_BINARY', 'PREFER_NOT_TO_SAY', 'OTHER']),
      preferredActivities: a.string().array(),

      // New Profile fields
      username: a.string(), // For a unique @handle
      bio: a.string(),
      profilePictureKey: a.string(), // Key for S3 storage
      
      // Relationships
      activities: a.hasMany('Activity', 'owner'),
      clubs: a.hasMany('ClubMember', 'userId'),
      rsvps: a.hasMany('EventRSVP', 'userId'),
      
      // Follower/Following relationships
      following: a.hasMany('Follow', 'followedId'),
      followers: a.hasMany('Follow', 'followerId'),

      owner: a.string()
        .required()
        .authorization(allow => [
          allow.owner(),
          allow.authenticated().to(['read'])
        ]),
    })
    .authorization((allow) => [
      allow.owner(),
      allow.authenticated().to(['read'])
    ]),

  Follow: a.model({
    followerId: a.id().required(),
    followedId: a.id().required(),

    follower: a.belongsTo('User', 'followerId'),
    followed: a.belongsTo('User', 'followedId'),
  }).authorization(allow => [allow.owner()]), // Only the follower can create/delete their follow

  // --- CLUBS & EVENTS (Module 4) ---
  Club: a.model({
    name: a.string().required(),
    description: a.string(),
    location: a.string(),
    coverImageKey: a.string(),
    
    // Relationships
    members: a.hasMany('ClubMember', 'clubId'),
    events: a.hasMany('Event', 'clubId'),
    
    // The club owner/admin
    owner: a.string().required().authorization(allow => [
      allow.owner(),
      allow.authenticated().to(['read'])
    ]),

  }).authorization(allow => [
    allow.owner(), // Owner can update/delete
    allow.authenticated().to(['read']) // authenticated can read
  ]),

  // Join table for Users and Clubs
  ClubMember: a.model({
        
    clubId: a.id().required(),
    userId: a.id().required(),

    club: a.belongsTo('Club', 'clubId'),
    user: a.belongsTo('User', 'userId'),
    role: a.enum(['MEMBER', 'ADMIN']),
  }).authorization(allow => [
    allow.owner().to(['update', 'delete']), 
    allow.authenticated().to(['read'])
  ]),

  Event: a.model({
    title: a.string().required(),
    description: a.string(),
    dateTime: a.datetime().required(),
    meetingPoint: a.string(),
    
    // Relationships
    clubId: a.id().required(),
    club: a.belongsTo('Club', 'clubId'),
    rsvps: a.hasMany('EventRSVP', 'eventId'),
    linkedExperiences: a.hasMany('Activity', 'eventId'),
  }).authorization(allow => [
    allow.owner(), // Event creator (club admin)
    allow.authenticated().to(['read'])
  ]),

  // Join table for Users and Events
  EventRSVP: a.model({
    eventId: a.id().required(),
    event: a.belongsTo('Event', 'eventId'),
    userId: a.id().required(),
    user: a.belongsTo('User', 'userId'),
  }).authorization(allow => [allow.owner()]), // Only the user can RSVP for themselves

  // --- ACTIVITY & JOURNAL (Module 2 & 5) ---
  Activity: a.model({
    type: a.enum(['RUN', 'HIKE', 'CYCLE', 'WALK']), // Added WALK from screenshot
    distance: a.float(),
    duration: a.integer(), // in seconds
    gpxFileKey: a.string(), // Key for S3
    
    // The Journal / "Experience Vault"
    experienceTitle: a.string(),
    aiNarrative: a.string(), // Generated by Module 3
    media: a.hasMany('Media', 'activityId'),
    
    // Link to an event
    eventId: a.id(),
    event: a.belongsTo('Event', 'eventId'),

    user: a.belongsTo('User', 'owner'),    
    owner: a.string().required().authorization(allow => [
      allow.owner(),
      allow.authenticated().to(['read'])
  ]),
    
  }).authorization(allow => [
    allow.owner(),
    allow.authenticated().to(['read']) // Allow authenticated read for sharing
  ]),

  Media: a.model({
    type: a.enum(['AUDIO', 'VIDEO', 'PHOTO']),
    s3Key: a.string().required(),
    timestamp: a.datetime(),
    transcription: a.string(), // From Whisper
    detectedObjects: a.string().array(), // From YOLOV8
    
    activityId: a.id().required(),
    activity: a.belongsTo('Activity', 'activityId'),
    
    owner: a.string().required().authorization(allow => [allow.owner()]),
  }).authorization(allow => [allow.owner()]),
});


export type Schema = ClientSchema<typeof schema>;

export const data = defineData({
  schema,
  authorizationModes: {
    defaultAuthorizationMode: "userPool"
  },
});
